---
- name: "Hosts - tasks common for all hosts"
  hosts: all
  become: yes

  roles:
    - roles/common 

- name: "[ETCD]"
  hosts: etcd
  become: yes

  roles: 
    - roles/etcd

- name: "[Master]"
  hosts: master
  become: yes

  roles:
    - roles/master
    - roles/keepalived
